name: Publish to PyPI

on:
  release:
    types: [released]

jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      upload_to_pypi: ${{ (github.event_name == 'release') && (github.event.action == 'released') }}
    secrets:
      # WARNING: Do not hardcode secret values here!
      # If you want to use a different user or password, you can override this secret by creating
      # one with the same name in your Github repository settings.
      user: ${{ secrets.PYPI_USERNAME_ASDF_MAINTAINER }}
      password: ${{ secrets.PYPI_PASSWORD_ASDF_MAINTAINER }}
